threshold = 80
toLower = false

[[indices]]
    name = "categories"
    weight = 100

[[indices]]
    name = "tags"
    weight = 80

[[indices]]
    name = "date"
    pattern = "2006"
    weight = 10
